name: ramin-hello-world
summary: a sample hello world echo program
description: |
      trying to learn snap. This will echo hello world.
version: '0.2.0'
base: core22
confinement: strict

parts:
  ramin-hello-world:
    plugin: python
    source: .

apps:
  ramin-hello-world:
    command: bin/ramin-hello-world
    plugs: [home]
